{
 "title": "Power",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Totals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Peak Take",
     "limit": "1",
     "measurement": "p1_human",
     "query": "SELECT \"1-0:1.8.1\" FROM \"p1\" WHERE $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "meter_t1_used" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Off Peak Take",
     "limit": "1",
     "measurement": "p1_human",
     "query": "SELECT \"1-0:1.8.2\" FROM \"p1\" WHERE $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "meter_t2_used" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Peak Give",
     "limit": "1",
     "measurement": "p1_human",
     "select": [
      [
       { "params": [ "meter_t1_injected" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Off Peak Give",
     "limit": "1",
     "measurement": "p1_human",
     "query": "SELECT \"1-0:2.8.2\" FROM \"p1\" WHERE $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "meter_t2_injected" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Take",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "p1_human",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "power_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Give",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "p1_human",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "power_injected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak / Off Peak",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "p1_human",
     "select": [
      [
       { "params": [ "tariff" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p1_human",
     "select": [
      [
       { "params": [ "voltage_l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p1_human",
     "select": [
      [
       { "params": [ "current_l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Take",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p1_human",
     "query": "SELECT mean(\"1-0:1.7.0\") FROM \"p1\" WHERE $timeFilter GROUP BY time($interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "power_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Give",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p1_human",
     "query": "SELECT mean(\"1-0:2.7.0\") FROM \"p1\" WHERE $timeFilter GROUP BY time($interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "power_injected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}