name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: dries007
        password: ${{ secrets.PAT }}
    - name: Build:dockerimage
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: dries007/p1logger:latest
